# Generated by Django 4.1 on 2024-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_category_active_category_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
