# Generated by Django 4.1 on 2024-03-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_category_image_course_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="name",),
    ]
