# Generated by Django 4.1 on 2024-03-05 08:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
