# Generated by Django 4.1 on 2024-03-05 08:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
