# Generated by Django 4.1 on 2024-03-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_category_name_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
